services:
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=video
    volumes:
      - postgresdata:/var/lib/postgresql/data/
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
  postgresdata: