# Generated by Django 3.2.8 on 2021-10-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_count_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtask',
            options={'permissions': [('test_1-2', 'test 1 2'), ('test_3_4', 'Test 3 4')]},
        ),
    ]
