# Generated by Django 3.2.8 on 2021-10-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_testtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='count_view',
            field=models.IntegerField(default=0),
        ),
    ]
